/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserProfileRouteImport } from './routes/user-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RoutinesIndexRouteImport } from './routes/routines/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as ProgressIndexRouteImport } from './routes/progress/index'
import { Route as MealsIndexRouteImport } from './routes/meals/index'
import { Route as FaqsIndexRouteImport } from './routes/faqs/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as RoutinesCreateRouteImport } from './routes/routines/create'
import { Route as RecipesCreateRouteImport } from './routes/recipes/create'
import { Route as MealsCreateRouteImport } from './routes/meals/create'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as RoutinesUpdateRoutineIdRouteImport } from './routes/routines/update/$routineId'
import { Route as RoutinesRoutineDetailsRoutineIdRouteImport } from './routes/routines/routine-details/$routineId'
import { Route as RecipesUpdateRecipeIdRouteImport } from './routes/recipes/update/$recipeId'
import { Route as MealsUpdateMealIdRouteImport } from './routes/meals/update/$mealId'
import { Route as MealsDetailsMealIdRouteImport } from './routes/meals/details/$mealId'

const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/meals/',
  path: '/meals/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsIndexRoute = FaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesCreateRoute = RoutinesCreateRouteImport.update({
  id: '/routines/create',
  path: '/routines/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesCreateRoute = RecipesCreateRouteImport.update({
  id: '/recipes/create',
  path: '/recipes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsCreateRoute = MealsCreateRouteImport.update({
  id: '/meals/create',
  path: '/meals/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesUpdateRoutineIdRoute = RoutinesUpdateRoutineIdRouteImport.update({
  id: '/routines/update/$routineId',
  path: '/routines/update/$routineId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoutineDetailsRoutineIdRoute =
  RoutinesRoutineDetailsRoutineIdRouteImport.update({
    id: '/routines/routine-details/$routineId',
    path: '/routines/routine-details/$routineId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecipesUpdateRecipeIdRoute = RecipesUpdateRecipeIdRouteImport.update({
  id: '/recipes/update/$recipeId',
  path: '/recipes/update/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsUpdateMealIdRoute = MealsUpdateMealIdRouteImport.update({
  id: '/meals/update/$mealId',
  path: '/meals/update/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsDetailsMealIdRoute = MealsDetailsMealIdRouteImport.update({
  id: '/meals/details/$mealId',
  path: '/meals/details/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user-profile': typeof UserProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/meals/create': typeof MealsCreateRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/routines/create': typeof RoutinesCreateRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/faqs': typeof FaqsIndexRoute
  '/meals': typeof MealsIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/meals/details/$mealId': typeof MealsDetailsMealIdRoute
  '/meals/update/$mealId': typeof MealsUpdateMealIdRoute
  '/recipes/update/$recipeId': typeof RecipesUpdateRecipeIdRoute
  '/routines/routine-details/$routineId': typeof RoutinesRoutineDetailsRoutineIdRoute
  '/routines/update/$routineId': typeof RoutinesUpdateRoutineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user-profile': typeof UserProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/meals/create': typeof MealsCreateRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/routines/create': typeof RoutinesCreateRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/faqs': typeof FaqsIndexRoute
  '/meals': typeof MealsIndexRoute
  '/progress': typeof ProgressIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/meals/details/$mealId': typeof MealsDetailsMealIdRoute
  '/meals/update/$mealId': typeof MealsUpdateMealIdRoute
  '/recipes/update/$recipeId': typeof RecipesUpdateRecipeIdRoute
  '/routines/routine-details/$routineId': typeof RoutinesRoutineDetailsRoutineIdRoute
  '/routines/update/$routineId': typeof RoutinesUpdateRoutineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user-profile': typeof UserProfileRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/meals/create': typeof MealsCreateRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/routines/create': typeof RoutinesCreateRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/faqs/': typeof FaqsIndexRoute
  '/meals/': typeof MealsIndexRoute
  '/progress/': typeof ProgressIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/meals/details/$mealId': typeof MealsDetailsMealIdRoute
  '/meals/update/$mealId': typeof MealsUpdateMealIdRoute
  '/recipes/update/$recipeId': typeof RecipesUpdateRecipeIdRoute
  '/routines/routine-details/$routineId': typeof RoutinesRoutineDetailsRoutineIdRoute
  '/routines/update/$routineId': typeof RoutinesUpdateRoutineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user-profile'
    | '/admin/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/meals/create'
    | '/recipes/create'
    | '/routines/create'
    | '/settings/security'
    | '/faqs'
    | '/meals'
    | '/progress'
    | '/recipes'
    | '/routines'
    | '/settings'
    | '/meals/details/$mealId'
    | '/meals/update/$mealId'
    | '/recipes/update/$recipeId'
    | '/routines/routine-details/$routineId'
    | '/routines/update/$routineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user-profile'
    | '/admin/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/meals/create'
    | '/recipes/create'
    | '/routines/create'
    | '/settings/security'
    | '/faqs'
    | '/meals'
    | '/progress'
    | '/recipes'
    | '/routines'
    | '/settings'
    | '/meals/details/$mealId'
    | '/meals/update/$mealId'
    | '/recipes/update/$recipeId'
    | '/routines/routine-details/$routineId'
    | '/routines/update/$routineId'
  id:
    | '__root__'
    | '/'
    | '/user-profile'
    | '/admin/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/meals/create'
    | '/recipes/create'
    | '/routines/create'
    | '/settings/security'
    | '/faqs/'
    | '/meals/'
    | '/progress/'
    | '/recipes/'
    | '/routines/'
    | '/settings/'
    | '/meals/details/$mealId'
    | '/meals/update/$mealId'
    | '/recipes/update/$recipeId'
    | '/routines/routine-details/$routineId'
    | '/routines/update/$routineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserProfileRoute: typeof UserProfileRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  MealsCreateRoute: typeof MealsCreateRoute
  RecipesCreateRoute: typeof RecipesCreateRoute
  RoutinesCreateRoute: typeof RoutinesCreateRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  FaqsIndexRoute: typeof FaqsIndexRoute
  MealsIndexRoute: typeof MealsIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  MealsDetailsMealIdRoute: typeof MealsDetailsMealIdRoute
  MealsUpdateMealIdRoute: typeof MealsUpdateMealIdRoute
  RecipesUpdateRecipeIdRoute: typeof RecipesUpdateRecipeIdRoute
  RoutinesRoutineDetailsRoutineIdRoute: typeof RoutinesRoutineDetailsRoutineIdRoute
  RoutinesUpdateRoutineIdRoute: typeof RoutinesUpdateRoutineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-profile': {
      id: '/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/': {
      id: '/meals/'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/': {
      id: '/faqs/'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/create': {
      id: '/routines/create'
      path: '/routines/create'
      fullPath: '/routines/create'
      preLoaderRoute: typeof RoutinesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/create': {
      id: '/recipes/create'
      path: '/recipes/create'
      fullPath: '/recipes/create'
      preLoaderRoute: typeof RecipesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/create': {
      id: '/meals/create'
      path: '/meals/create'
      fullPath: '/meals/create'
      preLoaderRoute: typeof MealsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/update/$routineId': {
      id: '/routines/update/$routineId'
      path: '/routines/update/$routineId'
      fullPath: '/routines/update/$routineId'
      preLoaderRoute: typeof RoutinesUpdateRoutineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/routine-details/$routineId': {
      id: '/routines/routine-details/$routineId'
      path: '/routines/routine-details/$routineId'
      fullPath: '/routines/routine-details/$routineId'
      preLoaderRoute: typeof RoutinesRoutineDetailsRoutineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/update/$recipeId': {
      id: '/recipes/update/$recipeId'
      path: '/recipes/update/$recipeId'
      fullPath: '/recipes/update/$recipeId'
      preLoaderRoute: typeof RecipesUpdateRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/update/$mealId': {
      id: '/meals/update/$mealId'
      path: '/meals/update/$mealId'
      fullPath: '/meals/update/$mealId'
      preLoaderRoute: typeof MealsUpdateMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/details/$mealId': {
      id: '/meals/details/$mealId'
      path: '/meals/details/$mealId'
      fullPath: '/meals/details/$mealId'
      preLoaderRoute: typeof MealsDetailsMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserProfileRoute: UserProfileRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  MealsCreateRoute: MealsCreateRoute,
  RecipesCreateRoute: RecipesCreateRoute,
  RoutinesCreateRoute: RoutinesCreateRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  FaqsIndexRoute: FaqsIndexRoute,
  MealsIndexRoute: MealsIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  MealsDetailsMealIdRoute: MealsDetailsMealIdRoute,
  MealsUpdateMealIdRoute: MealsUpdateMealIdRoute,
  RecipesUpdateRecipeIdRoute: RecipesUpdateRecipeIdRoute,
  RoutinesRoutineDetailsRoutineIdRoute: RoutinesRoutineDetailsRoutineIdRoute,
  RoutinesUpdateRoutineIdRoute: RoutinesUpdateRoutineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
